apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-admin-bind
roleRef:
  kind: ClusterRole
  name: devops-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: devops-admin
    apiGroup: rbac.authorization.k8s.io
