apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ssh-app
  template:
    metadata:
      labels:
        app: ssh-app
    spec:
      containers:
        - name: ubuntu
          image: 654654232198.dkr.ecr.us-east-1.amazonaws.com/base.image/ubuntu:latest
          ports:
            - containerPort: 22


