apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: ssh-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
