name: Terraform apply only when Infra folder get update

on:
  push:
    branches:
      - main
    paths:
      - 'Infra/**'  # Trigger only when files in Infra folder are modified
  workflow_dispatch: # Enabled manual triggering 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6
      
      - name: setup aws credentials
        run: |
          echo AWS_ACCESS_KEY_ID={{ secrets.AWS_ACCESS_KEY_ID }} >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY={{ secrets.AWS_SECRET_ACCESS_KEY }} >> $GITHUB_ENV
          env | grep AWS
     
      - name: terraform action
        run: |
          terraform init
          terraform plan
          terraform apply --auto-approve
        working-directory: ./Infra
        
      